### ISSUE TITLE
Impossible to install generators on Yo v.1.8.1

### ISSUE THREAD

**Issue by andreasonny83** [yeoman/yo#431]
Updating to the latest Yo version I'm now unable to install generators.
Ex. trying to `npm install -g generator-generator`
When I run `yo generator`, all I can see is this:
![1__node](https://cloud.githubusercontent.com/assets/8806300/15124273/41f3ca42-161f-11e6-80c9-0e4c920e9642.png)

Then I need to manually end the process and forget about generators.

I also created a generator-mdl hosted on GitHub at: https://github.com/andreasonny83/generator-mdl
This was working on Yo version 1.6 but now, running yo v1.8.1, it ask me for the project name, then it exits without installing anything.

----
```
yo --version: 1.8.1
echo $PATH $NODE_PATH: /usr/local/lib/node_modules:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
node -e 'console.log(process.platform, process.versions): 
darwin { 
  http_parser: '2.6.0',
  node: '5.5.0',
  v8: '4.6.85.31',
  uv: '1.8.0',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  icu: '56.1',
  modules: '47',
  openssl: '1.0.2e' 
}
```
----

**Comment by SBoudrias** [comment]
But so the generator installed? It just nothing works afterwards?

Does it work when you downgrade to yo 1.7?

**Comment by andreasonny83** [comment]
No, the generators are not installed and once upgraded to 1.8.1 even if I uninstall the global package and I install an older version, the issue persists. No idea what to do. I reproduced the same issue also on a different machine.

**Comment by SBoudrias** [comment]
Did you try running `yo doctor`?

**Comment by andreasonny83** [comment]
yes, `yo doctor` says everything is all right:
```
Yeoman Doctor
Running sanity checks on your system

✔ Global configuration file is valid
✔ NODE_PATH matches the npm root
✔ Node.js version
✔ No .bowerrc file in home directory
✔ No .yo-rc.json file in home directory
✔ npm version
```

I'm available for a [tmate](https://tmate.io/) session if you want to dig deep in my issue

**Comment by SBoudrias** [comment]
Okay, so generator-generator is making a call to the npm API to check if a name is available.

This is an asynchronous call and will delay the next prompt until resolution. So a few thing might go wrong for you:

1. The internet is super slow - maybe wait a bit longer?
2. You're behind a proxy that might be blocking the API call - I've seen some proxy across the years where calls were not being closed by the proxy as unallowed. In other words, the proxy would force any network calls to the blocked domain to timeout instead of error out.
3. There's an error happening somewhere and for some reason our code is swallowing it.

Hopefully that'll be helpful. I'll release a new version on generator-generator tonight. You should try on the latest version, I believe we fixed some errors being swallowed issue with the latest core release.

**Comment by andreasonny83** [comment]
Thanks for your help but I've already considered those options and:
1. I have a 20Mb/s connection
2. I tried to forget about the terminal and came back in 20 minutes but nothing happened. It still shows the screenshot I shared.
3. As I said, I managed to reproduce the same issue on another machine placed in a different location and using a different Internet provider

**Comment by andreasonny83** [comment]
I just noticed I can successfully install some generators. I just tried generator-angular and that worked fine.

**Comment by andreasonny83** [comment]
I'm in my office now and generator-generator is working here on yo 1.8.1. I will close this card for now and continue the investigations on my 2 personal machines. Thanks for your help.
